name: Build and Push Docker Images

on:
  push:
    branches:
      - main

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # --------------------
      # Build & Push Backend
      # --------------------
      - name: Build & Push Backend
        uses: docker/build-push-action@v5
        with:
          context: ./classroom-backend
          file: ./classroom-backend/Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/classroom-backend:latest
            ${{ secrets.DOCKER_USERNAME }}/classroom-backend:${{ github.sha }}

      # --------------------
      # Build & Push Frontend
      # --------------------
      - name: Build & Push Frontend
        uses: docker/build-push-action@v5
        with:
          context: ./classroom-frontend
          file: ./classroom-frontend/Dockerfile
          push: true
          build-args: |
            VITE_CLOUDINARY_CLOUD_NAME=${{ secrets.VITE_CLOUDINARY_CLOUD_NAME }}
            VITE_CLOUDINARY_UPLOAD_PRESET=${{ secrets.VITE_CLOUDINARY_UPLOAD_PRESET }}
            VITE_CLOUDINARY_UPLOAD_URL=${{ secrets.VITE_CLOUDINARY_UPLOAD_URL }}
            VITE_BACKEND_BASE_URL=http://localhost:8000/api/
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/classroom-frontend:latest
            ${{ secrets.DOCKER_USERNAME }}/classroom-frontend:${{ github.sha }}
